import type { Icon as PhosphorIcon, IconWeight } from '@phosphor-icons/react';
import {
  AddressBookIcon,
  ArrowClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowsLeftRightIcon,
  BookmarkSimpleIcon,
  BrainIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CaretDownIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  ChatCircleDotsIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleIcon,
  CpuIcon,
  DatabaseIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderIcon,
  FunnelIcon,
  GaugeIcon,
  GitMergeIcon,
  GraphIcon,
  HeartbeatIcon,
  HourglassMediumIcon,
  IdentificationCardIcon,
  InfoIcon,
  KeyIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  NotebookIcon,
  PasswordIcon,
  PenNibIcon,
  PlugsConnectedIcon,
  PlugsIcon,
  PuzzlePieceIcon,
  RobotIcon,
  RocketLaunchIcon,
  ShieldCheckIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SlidersIcon,
  TargetIcon,
  TranslateIcon,
  TrayIcon,
  UserFocusIcon,
  UsersThreeIcon,
  WarningCircleIcon,
  XIcon,
} from '@phosphor-icons/react';

/**
 * Phosphor web class → React component. The API and the design both name
 * icons with web-font classes ("ph ph-gauge", "ph-fill ph-briefcase"); this
 * keeps that vocabulary while rendering SVGs from @phosphor-icons/react.
 */
export const ICONS: Record<string, PhosphorIcon> = {
  'address-book': AddressBookIcon,
  'arrow-clockwise': ArrowClockwiseIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'arrows-left-right': ArrowsLeftRightIcon,
  'bookmark-simple': BookmarkSimpleIcon,
  brain: BrainIcon,
  briefcase: BriefcaseIcon,
  buildings: BuildingsIcon,
  'caret-down': CaretDownIcon,
  'caret-right': CaretRightIcon,
  'caret-up-down': CaretUpDownIcon,
  'chat-circle-dots': ChatCircleDotsIcon,
  check: CheckIcon,
  'check-circle': CheckCircleIcon,
  circle: CircleIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  eye: EyeIcon,
  'eye-slash': EyeSlashIcon,
  folder: FolderIcon,
  funnel: FunnelIcon,
  gauge: GaugeIcon,
  'git-merge': GitMergeIcon,
  graph: GraphIcon,
  heartbeat: HeartbeatIcon,
  'hourglass-medium': HourglassMediumIcon,
  'identification-card': IdentificationCardIcon,
  info: InfoIcon,
  key: KeyIcon,
  'lock-simple': LockSimpleIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  notebook: NotebookIcon,
  password: PasswordIcon,
  'pen-nib': PenNibIcon,
  plugs: PlugsIcon,
  'plugs-connected': PlugsConnectedIcon,
  'puzzle-piece': PuzzlePieceIcon,
  robot: RobotIcon,
  'rocket-launch': RocketLaunchIcon,
  'shield-check': ShieldCheckIcon,
  'sidebar-simple': SidebarSimpleIcon,
  'sign-out': SignOutIcon,
  sliders: SlidersIcon,
  'sliders-horizontal': SlidersHorizontalIcon,
  target: TargetIcon,
  translate: TranslateIcon,
  tray: TrayIcon,
  'user-focus': UserFocusIcon,
  'users-three': UsersThreeIcon,
  'warning-circle': WarningCircleIcon,
  x: XIcon,
};

export function parseIconClass(cls: string): { name: string; weight: IconWeight } {
  const parts = cls.trim().split(/\s+/);
  const weight: IconWeight = parts.includes('ph-fill') ? 'fill' : 'regular';
  const nameCls = parts.find((p) => p.startsWith('ph-') && p !== 'ph-fill') ?? '';
  return { name: nameCls.replace(/^ph-/, ''), weight };
}

export function hasIcon(cls: string): boolean {
  return parseIconClass(cls).name in ICONS;
}
