import type { Icon as PhosphorIcon, IconWeight } from '@phosphor-icons/react';
import {
  AddressBookIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  ArrowsLeftRightIcon,
  AtomIcon,
  BookmarkSimpleIcon,
  BrainIcon,
  BriefcaseIcon,
  BroadcastIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  CaretUpIcon,
  ChatCircleDotsIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleIcon,
  CircleNotchIcon,
  ClockCounterClockwiseIcon,
  CopyIcon,
  CpuIcon,
  DatabaseIcon,
  DeviceMobileIcon,
  DotsSixVerticalIcon,
  DownloadSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FlaskIcon,
  FlowArrowIcon,
  FolderIcon,
  FunnelIcon,
  GaugeIcon,
  GearIcon,
  GitMergeIcon,
  GraphIcon,
  HeartbeatIcon,
  HourglassIcon,
  HourglassMediumIcon,
  IdentificationCardIcon,
  InfoIcon,
  KeyIcon,
  LinkIcon,
  LinkedinLogoIcon,
  ListChecksIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MinusCircleIcon,
  NotebookIcon,
  PaperPlaneTiltIcon,
  PasswordIcon,
  PenNibIcon,
  PencilSimpleIcon,
  PlayIcon,
  PlugsConnectedIcon,
  PlugsIcon,
  PlusIcon,
  ProhibitIcon,
  PushPinIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  QuotesIcon,
  RobotIcon,
  RocketLaunchIcon,
  ScissorsIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SlidersIcon,
  TargetIcon,
  TranslateIcon,
  TrashIcon,
  TrayIcon,
  UserFocusIcon,
  UserIcon,
  UserSwitchIcon,
  UsersThreeIcon,
  WarningCircleIcon,
  WarningIcon,
  XCircleIcon,
  XIcon,
} from '@phosphor-icons/react';

/**
 * Phosphor web class → React component. The API and the design both name
 * icons with web-font classes ("ph ph-gauge", "ph-fill ph-briefcase"); this
 * keeps that vocabulary while rendering SVGs from @phosphor-icons/react.
 */
export const ICONS: Record<string, PhosphorIcon> = {
  'address-book': AddressBookIcon,
  'arrow-clockwise': ArrowClockwiseIcon,
  'arrow-counter-clockwise': ArrowCounterClockwiseIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-square-out': ArrowSquareOutIcon,
  'arrow-up': ArrowUpIcon,
  'arrows-clockwise': ArrowsClockwiseIcon,
  'arrows-left-right': ArrowsLeftRightIcon,
  atom: AtomIcon,
  'bookmark-simple': BookmarkSimpleIcon,
  brain: BrainIcon,
  briefcase: BriefcaseIcon,
  broadcast: BroadcastIcon,
  buildings: BuildingsIcon,
  'calendar-blank': CalendarBlankIcon,
  'caret-double-right': CaretDoubleRightIcon,
  'caret-down': CaretDownIcon,
  'caret-right': CaretRightIcon,
  'caret-up': CaretUpIcon,
  'caret-up-down': CaretUpDownIcon,
  'chat-circle-dots': ChatCircleDotsIcon,
  check: CheckIcon,
  'check-circle': CheckCircleIcon,
  circle: CircleIcon,
  'circle-notch': CircleNotchIcon,
  'clock-counter-clockwise': ClockCounterClockwiseIcon,
  copy: CopyIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  'device-mobile': DeviceMobileIcon,
  'dots-six-vertical': DotsSixVerticalIcon,
  'download-simple': DownloadSimpleIcon,
  eye: EyeIcon,
  'eye-slash': EyeSlashIcon,
  flask: FlaskIcon,
  'flow-arrow': FlowArrowIcon,
  folder: FolderIcon,
  funnel: FunnelIcon,
  gauge: GaugeIcon,
  gear: GearIcon,
  'git-merge': GitMergeIcon,
  graph: GraphIcon,
  heartbeat: HeartbeatIcon,
  hourglass: HourglassIcon,
  'hourglass-medium': HourglassMediumIcon,
  'identification-card': IdentificationCardIcon,
  info: InfoIcon,
  key: KeyIcon,
  link: LinkIcon,
  'linkedin-logo': LinkedinLogoIcon,
  'list-checks': ListChecksIcon,
  'lock-simple': LockSimpleIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  'minus-circle': MinusCircleIcon,
  notebook: NotebookIcon,
  'paper-plane-tilt': PaperPlaneTiltIcon,
  password: PasswordIcon,
  'pen-nib': PenNibIcon,
  'pencil-simple': PencilSimpleIcon,
  play: PlayIcon,
  plugs: PlugsIcon,
  'plugs-connected': PlugsConnectedIcon,
  plus: PlusIcon,
  prohibit: ProhibitIcon,
  'push-pin': PushPinIcon,
  'puzzle-piece': PuzzlePieceIcon,
  'qr-code': QrCodeIcon,
  quotes: QuotesIcon,
  robot: RobotIcon,
  'rocket-launch': RocketLaunchIcon,
  scissors: ScissorsIcon,
  'shield-check': ShieldCheckIcon,
  'shield-warning': ShieldWarningIcon,
  'sidebar-simple': SidebarSimpleIcon,
  'sign-out': SignOutIcon,
  sliders: SlidersIcon,
  'sliders-horizontal': SlidersHorizontalIcon,
  target: TargetIcon,
  translate: TranslateIcon,
  trash: TrashIcon,
  tray: TrayIcon,
  user: UserIcon,
  'user-focus': UserFocusIcon,
  'user-switch': UserSwitchIcon,
  'users-three': UsersThreeIcon,
  warning: WarningIcon,
  'warning-circle': WarningCircleIcon,
  x: XIcon,
  'x-circle': XCircleIcon,
};

export function parseIconClass(cls: string): { name: string; weight: IconWeight } {
  const parts = cls.trim().split(/\s+/);
  const weight: IconWeight = parts.includes('ph-fill') ? 'fill' : 'regular';
  const nameCls = parts.find((p) => p.startsWith('ph-') && p !== 'ph-fill') ?? '';
  return { name: nameCls.replace(/^ph-/, ''), weight };
}

export function hasIcon(cls: string): boolean {
  return parseIconClass(cls).name in ICONS;
}
