import type { Icon as PhosphorIcon, IconWeight } from '@phosphor-icons/react';
import {
  AlarmIcon,
  ArchiveIcon,
  ArrowBendUpLeftIcon,
  ArrowDownRightIcon,
  ArrowLineUpRightIcon,
  ArrowUpRightIcon,
  ArrowsDownUpIcon,
  ArrowsInIcon,
  ArrowsInLineHorizontalIcon,
  ArrowsOutIcon,
  BankIcon,
  BellIcon,
  BellRingingIcon,
  BellSlashIcon,
  BookOpenIcon,
  BrowserIcon,
  CalendarCheckIcon,
  CalendarIcon,
  CalendarPlusIcon,
  ChalkboardTeacherIcon,
  ChartBarIcon,
  ChartDonutIcon,
  ChartLineIcon,
  ChartLineUpIcon,
  ChartPieIcon,
  ChatTextIcon,
  ChatsIcon,
  CheckSquareIcon,
  CheckSquareOffsetIcon,
  CirclesThreeIcon,
  ClipboardTextIcon,
  ClockCountdownIcon,
  ClockIcon,
  CrosshairIcon,
  CrownSimpleIcon,
  CubeIcon,
  CubeTransparentIcon,
  CurrencyCircleDollarIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  EnvelopeIcon,
  FileDocIcon,
  FilePdfIcon,
  FileTextIcon,
  FileXlsIcon,
  FilesIcon,
  FingerprintIcon,
  FireIcon,
  FlagIcon,
  FloppyDiskIcon,
  FolderOpenIcon,
  FoldersIcon,
  FunnelSimpleIcon,
  GavelIcon,
  GitBranchIcon,
  GlobeHemisphereEastIcon,
  HandshakeIcon,
  HashIcon,
  HeartIcon,
  IdentificationBadgeIcon,
  KanbanIcon,
  LifebuoyIcon,
  LightbulbIcon,
  LinkBreakIcon,
  ListIcon,
  LockIcon,
  LockKeyIcon,
  LockOpenIcon,
  MagicWandIcon,
  MapTrifoldIcon,
  MinusIcon,
  MoonIcon,
  NoteIcon,
  NotePencilIcon,
  PackageIcon,
  PaperclipIcon,
  PhoneIcon,
  PlusCircleIcon,
  PolygonIcon,
  PulseIcon,
  PushPinSlashIcon,
  QuestionIcon,
  ReceiptIcon,
  RowsIcon,
  ScalesIcon,
  SealCheckIcon,
  ShoppingCartIcon,
  SirenIcon,
  SmileyIcon,
  SnowflakeIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparkleIcon,
  SquaresFourIcon,
  StackIcon,
  StarIcon,
  StethoscopeIcon,
  StorefrontIcon,
  TableIcon,
  TagIcon,
  TelegramLogoIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TreeIcon,
  TreeStructureIcon,
  TrendDownIcon,
  TrendUpIcon,
  TrophyIcon,
  TruckIcon,
  UploadSimpleIcon,
  UserCircleIcon,
  UserListIcon,
  UserPlusIcon,
  UsersIcon,
  WarningOctagonIcon,
  WaveformIcon,
  WebhooksLogoIcon,
  WhatsappLogoIcon,
} from '@phosphor-icons/react';
import {
  AddressBookIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  ArrowsLeftRightIcon,
  AtomIcon,
  BookmarkSimpleIcon,
  BrainIcon,
  BriefcaseIcon,
  BroadcastIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  CaretUpIcon,
  ChatCircleDotsIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleIcon,
  CircleNotchIcon,
  ClockCounterClockwiseIcon,
  CopyIcon,
  CpuIcon,
  DatabaseIcon,
  DeviceMobileIcon,
  DotsSixVerticalIcon,
  DownloadSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FlaskIcon,
  FlowArrowIcon,
  FolderIcon,
  FunnelIcon,
  GaugeIcon,
  GearIcon,
  GitMergeIcon,
  GraphIcon,
  HeartbeatIcon,
  HourglassIcon,
  HourglassMediumIcon,
  IdentificationCardIcon,
  InfoIcon,
  KeyIcon,
  LinkIcon,
  LinkedinLogoIcon,
  ListChecksIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MinusCircleIcon,
  NotebookIcon,
  PaperPlaneTiltIcon,
  PasswordIcon,
  PenNibIcon,
  PencilSimpleIcon,
  PlayIcon,
  PlugsConnectedIcon,
  PlugsIcon,
  PlusIcon,
  ProhibitIcon,
  PushPinIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  QuotesIcon,
  RobotIcon,
  RocketLaunchIcon,
  ScissorsIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SlidersIcon,
  TargetIcon,
  TranslateIcon,
  TrashIcon,
  TrayIcon,
  UserFocusIcon,
  UserIcon,
  UserSwitchIcon,
  UsersThreeIcon,
  WarningCircleIcon,
  WarningIcon,
  XCircleIcon,
  XIcon,
} from '@phosphor-icons/react';

/**
 * Phosphor web class → React component. The API and the design both name
 * icons with web-font classes ("ph ph-gauge", "ph-fill ph-briefcase"); this
 * keeps that vocabulary while rendering SVGs from @phosphor-icons/react.
 */
export const ICONS: Record<string, PhosphorIcon> = {
  'address-book': AddressBookIcon,
  alarm: AlarmIcon,
  archive: ArchiveIcon,
  'arrow-bend-up-left': ArrowBendUpLeftIcon,
  'arrow-clockwise': ArrowClockwiseIcon,
  'arrow-counter-clockwise': ArrowCounterClockwiseIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-down-right': ArrowDownRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-line-up-right': ArrowLineUpRightIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-square-out': ArrowSquareOutIcon,
  'arrow-up': ArrowUpIcon,
  'arrow-up-right': ArrowUpRightIcon,
  'arrows-clockwise': ArrowsClockwiseIcon,
  'arrows-down-up': ArrowsDownUpIcon,
  'arrows-in': ArrowsInIcon,
  'arrows-in-line-horizontal': ArrowsInLineHorizontalIcon,
  'arrows-left-right': ArrowsLeftRightIcon,
  'arrows-out': ArrowsOutIcon,
  atom: AtomIcon,
  bank: BankIcon,
  bell: BellIcon,
  'bell-ringing': BellRingingIcon,
  'bell-slash': BellSlashIcon,
  'book-open': BookOpenIcon,
  'bookmark-simple': BookmarkSimpleIcon,
  brain: BrainIcon,
  briefcase: BriefcaseIcon,
  broadcast: BroadcastIcon,
  browser: BrowserIcon,
  buildings: BuildingsIcon,
  calendar: CalendarIcon,
  'calendar-blank': CalendarBlankIcon,
  'calendar-check': CalendarCheckIcon,
  'calendar-plus': CalendarPlusIcon,
  'caret-double-right': CaretDoubleRightIcon,
  'caret-down': CaretDownIcon,
  'caret-right': CaretRightIcon,
  'caret-up': CaretUpIcon,
  'caret-up-down': CaretUpDownIcon,
  'chalkboard-teacher': ChalkboardTeacherIcon,
  'chart-bar': ChartBarIcon,
  'chart-donut': ChartDonutIcon,
  'chart-line': ChartLineIcon,
  'chart-line-up': ChartLineUpIcon,
  'chart-pie': ChartPieIcon,
  'chat-circle-dots': ChatCircleDotsIcon,
  'chat-text': ChatTextIcon,
  chats: ChatsIcon,
  check: CheckIcon,
  'check-circle': CheckCircleIcon,
  'check-square': CheckSquareIcon,
  'check-square-offset': CheckSquareOffsetIcon,
  circle: CircleIcon,
  'circle-notch': CircleNotchIcon,
  'circles-three': CirclesThreeIcon,
  'clipboard-text': ClipboardTextIcon,
  clock: ClockIcon,
  'clock-countdown': ClockCountdownIcon,
  'clock-counter-clockwise': ClockCounterClockwiseIcon,
  copy: CopyIcon,
  cpu: CpuIcon,
  crosshair: CrosshairIcon,
  'crown-simple': CrownSimpleIcon,
  cube: CubeIcon,
  'cube-transparent': CubeTransparentIcon,
  'currency-circle-dollar': CurrencyCircleDollarIcon,
  database: DatabaseIcon,
  'device-mobile': DeviceMobileIcon,
  'dots-six-vertical': DotsSixVerticalIcon,
  'dots-three': DotsThreeIcon,
  'dots-three-vertical': DotsThreeVerticalIcon,
  'download-simple': DownloadSimpleIcon,
  envelope: EnvelopeIcon,
  eye: EyeIcon,
  'eye-slash': EyeSlashIcon,
  'file-doc': FileDocIcon,
  'file-pdf': FilePdfIcon,
  'file-text': FileTextIcon,
  'file-xls': FileXlsIcon,
  files: FilesIcon,
  fingerprint: FingerprintIcon,
  fire: FireIcon,
  flag: FlagIcon,
  flask: FlaskIcon,
  'floppy-disk': FloppyDiskIcon,
  'flow-arrow': FlowArrowIcon,
  folder: FolderIcon,
  'folder-open': FolderOpenIcon,
  folders: FoldersIcon,
  funnel: FunnelIcon,
  'funnel-simple': FunnelSimpleIcon,
  gauge: GaugeIcon,
  gavel: GavelIcon,
  gear: GearIcon,
  'git-branch': GitBranchIcon,
  'git-merge': GitMergeIcon,
  'globe-hemisphere-east': GlobeHemisphereEastIcon,
  graph: GraphIcon,
  handshake: HandshakeIcon,
  hash: HashIcon,
  heart: HeartIcon,
  heartbeat: HeartbeatIcon,
  hourglass: HourglassIcon,
  'hourglass-medium': HourglassMediumIcon,
  'identification-badge': IdentificationBadgeIcon,
  'identification-card': IdentificationCardIcon,
  info: InfoIcon,
  kanban: KanbanIcon,
  key: KeyIcon,
  lifebuoy: LifebuoyIcon,
  lightbulb: LightbulbIcon,
  link: LinkIcon,
  'link-break': LinkBreakIcon,
  'linkedin-logo': LinkedinLogoIcon,
  list: ListIcon,
  'list-checks': ListChecksIcon,
  lock: LockIcon,
  'lock-key': LockKeyIcon,
  'lock-open': LockOpenIcon,
  'lock-simple': LockSimpleIcon,
  'magic-wand': MagicWandIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  'map-trifold': MapTrifoldIcon,
  minus: MinusIcon,
  'minus-circle': MinusCircleIcon,
  moon: MoonIcon,
  note: NoteIcon,
  'note-pencil': NotePencilIcon,
  notebook: NotebookIcon,
  package: PackageIcon,
  'paper-plane-tilt': PaperPlaneTiltIcon,
  paperclip: PaperclipIcon,
  password: PasswordIcon,
  'pen-nib': PenNibIcon,
  'pencil-simple': PencilSimpleIcon,
  phone: PhoneIcon,
  play: PlayIcon,
  plugs: PlugsIcon,
  'plugs-connected': PlugsConnectedIcon,
  plus: PlusIcon,
  'plus-circle': PlusCircleIcon,
  polygon: PolygonIcon,
  prohibit: ProhibitIcon,
  pulse: PulseIcon,
  'push-pin': PushPinIcon,
  'push-pin-slash': PushPinSlashIcon,
  'puzzle-piece': PuzzlePieceIcon,
  'qr-code': QrCodeIcon,
  question: QuestionIcon,
  quotes: QuotesIcon,
  receipt: ReceiptIcon,
  robot: RobotIcon,
  'rocket-launch': RocketLaunchIcon,
  rows: RowsIcon,
  scales: ScalesIcon,
  scissors: ScissorsIcon,
  'seal-check': SealCheckIcon,
  'shield-check': ShieldCheckIcon,
  'shield-warning': ShieldWarningIcon,
  'shopping-cart': ShoppingCartIcon,
  'sidebar-simple': SidebarSimpleIcon,
  'sign-out': SignOutIcon,
  siren: SirenIcon,
  sliders: SlidersIcon,
  'sliders-horizontal': SlidersHorizontalIcon,
  smiley: SmileyIcon,
  snowflake: SnowflakeIcon,
  'sort-ascending': SortAscendingIcon,
  'sort-descending': SortDescendingIcon,
  sparkle: SparkleIcon,
  'squares-four': SquaresFourIcon,
  stack: StackIcon,
  star: StarIcon,
  stethoscope: StethoscopeIcon,
  storefront: StorefrontIcon,
  table: TableIcon,
  tag: TagIcon,
  target: TargetIcon,
  'telegram-logo': TelegramLogoIcon,
  'thumbs-down': ThumbsDownIcon,
  'thumbs-up': ThumbsUpIcon,
  translate: TranslateIcon,
  trash: TrashIcon,
  tray: TrayIcon,
  tree: TreeIcon,
  'tree-structure': TreeStructureIcon,
  'trend-down': TrendDownIcon,
  'trend-up': TrendUpIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  'upload-simple': UploadSimpleIcon,
  user: UserIcon,
  'user-circle': UserCircleIcon,
  'user-focus': UserFocusIcon,
  'user-list': UserListIcon,
  'user-plus': UserPlusIcon,
  'user-switch': UserSwitchIcon,
  users: UsersIcon,
  'users-three': UsersThreeIcon,
  warning: WarningIcon,
  'warning-circle': WarningCircleIcon,
  'warning-octagon': WarningOctagonIcon,
  waveform: WaveformIcon,
  'webhooks-logo': WebhooksLogoIcon,
  'whatsapp-logo': WhatsappLogoIcon,
  x: XIcon,
  'x-circle': XCircleIcon,
};

export function parseIconClass(cls: string): { name: string; weight: IconWeight } {
  const parts = cls.trim().split(/\s+/);
  const weight: IconWeight = parts.includes('ph-fill') ? 'fill' : 'regular';
  const nameCls = parts.find((p) => p.startsWith('ph-') && p !== 'ph-fill') ?? '';
  return { name: nameCls.replace(/^ph-/, ''), weight };
}

export function hasIcon(cls: string): boolean {
  return parseIconClass(cls).name in ICONS;
}
